version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <pass>
    ports:
      - "9906:3306"

  php-fpm:
    build: './docker/php/'
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
      - 443:443
    links:
      - php-fpm
